# -*- coding: utf-8 -*-
"""Malzeme token -> Turkce isim sozlugu. 237 token."""

TOKEN_TR = {
    "spice": "baharat", "garlic": "sarımsak", "olive_oil": "zeytinyağı",
    "onion": "soğan", "butter": "tereyağı", "parsley": "maydanoz",
    "tomato": "domates", "lemon": "limon", "egg": "yumurta", "milk": "süt",
    "salt": "tuz", "cheese": "peynir", "thyme": "kekik", "flour": "un",
    "sugar": "şeker", "chicken": "tavuk", "vanilla": "vanilya", "yogurt": "yoğurt",
    "rice": "pirinç", "honey": "bal", "pepper": "biber", "bread": "ekmek",
    "potato": "patates", "beef": "dana eti", "almond": "badem", "walnut": "ceviz",
    "carrot": "havuç", "pasta": "makarna", "ginger": "zencefil", "fruit": "meyve",
    "cinnamon": "tarçın", "fish": "balık", "mushroom": "mantar", "cream": "krema",
    "sesame": "susam", "phyllo": "yufka", "basil": "fesleğen", "soy_sauce": "soya sosu",
    "vinegar": "sirke", "raisin": "kuru üzüm", "ground_meat": "kıyma",
    "chocolate": "çikolata", "spinach": "ıspanak", "water": "su", "oil": "sıvı yağ",
    "dill": "dereotu", "bulgur": "bulgur", "mint": "nane", "ground_beef": "dana kıyma",
    "olive": "zeytin", "yeast": "maya", "wine": "şarap", "zucchini": "kabak",
    "pistachio": "fıstık", "lamb": "kuzu eti", "vegetable": "sebze", "paprika": "toz biber",
    "white_bean": "kuru fasulye", "eggplant": "patlıcan", "tahini": "tahin",
    "tomato_paste": "domates salçası", "chili": "acı biber", "cornstarch": "mısır nişastası",
    "baking_powder": "kabartma tozu", "cucumber": "salatalık", "lentil": "mercimek",
    "cocoa": "kakao", "chickpea": "nohut", "shrimp": "karides", "scallion": "yeşil soğan",
    "bell_pepper": "dolmalık biber", "lettuce": "marul", "cumin": "kimyon",
    "pumpkin": "balkabağı", "feta": "beyaz peynir", "cookie": "bisküvi", "leek": "pırasa",
    "cabbage": "lahana", "smoked_meat": "füme et", "lime": "misket limonu", "oats": "yulaf",
    "parmesan": "parmesan", "molasses": "pekmez", "celery": "kereviz", "kaymak": "kaymak",
    "avocado": "avokado", "corn": "mısır", "pine_nut": "çam fıstığı", "semolina": "irmik",
    "cilantro": "kişniş", "saffron": "safran", "apple": "elma", "broccoli": "brokoli",
    "rosemary": "biberiye", "coconut": "hindistan cevizi", "rose_water": "gül suyu",
    "bacon": "domuz pastırması", "pomegranate": "nar", "white_wine": "beyaz şarap",
    "beet": "pancar", "cream_cheese": "krem peynir", "mayonnaise": "mayonez",
    "peas": "bezelye", "green_bean": "taze fasulye", "sumac": "sumak", "sausage": "sosis",
    "cardamom": "kakule", "beans": "fasulye", "green_pea": "yeşil bezelye",
    "mussel": "midye", "cauliflower": "karnabahar", "ham": "jambon", "mustard": "hardal",
    "balsamic": "balzamik sirke", "mozzarella": "mozzarella", "cornmeal": "mısır unu",
    "pork": "domuz eti", "orange": "portakal", "fish_sauce": "balık sosu",
    "coconut_milk": "hindistan cevizi sütü", "wheat": "buğday", "chia": "chia tohumu",
    "allspice": "yenibahar", "oregano": "kekik", "squid": "kalamar", "anchovy": "hamsi",
    "fava_bean": "bakla", "beetroot": "pancar", "banana": "muz", "pickle": "turşu",
    "hazelnut": "fındık", "vermicelli": "tel şehriye", "rice_noodle": "pirinç eriştesi",
    "yufka": "yufka", "tortilla": "tortilla", "octopus": "ahtapot", "salami": "salam",
    "edamame": "edamame", "gelatin": "jelatin", "grape_leaf": "asma yaprağı",
    "okra": "bamya", "berry": "orman meyvesi", "curry": "köri", "peanut": "yer fıstığı",
    "salmon": "somon", "sweet_potato": "tatlı patates", "breadcrumb": "galeta unu",
    "coffee": "kahve", "tea": "çay", "lemongrass": "limon otu", "coriander": "kişniş",
    "red_wine": "kırmızı şarap", "bean_sprout": "fasulye filizi", "blue_cheese": "küf peyniri",
    "panko": "panko galeta", "caper": "kapari", "tuna": "ton balığı",
    "grape_leaves": "asma yaprağı", "artichoke": "enginar", "quinoa": "kinoa",
    "arugula": "roka", "rum": "rom", "nutmeg": "muskat", "chives": "frenk soğanı",
    "tofu": "tofu", "granola": "granola", "bean": "fasulye", "sour_cream": "ekşi krema",
    "chicken_wing": "tavuk kanadı", "sage": "adaçayı", "nori": "nori yosunu",
    "couscous": "kuskus", "red_pepper": "kırmızı biber", "salep": "salep",
    "pandan": "pandan", "vegetables": "sebzeler", "ice": "buz", "currant": "kuş üzümü",
    "tarhana": "tarhana", "tripe": "işkembe", "green_lentil": "yeşil mercimek",
    "anise": "anason", "freekeh": "firik", "miso": "miso", "seaweed": "deniz yosunu",
    "ramen_noodle": "ramen eriştesi", "kidney_bean": "barbunya", "noodles": "erişte",
    "clam": "deniz tarağı", "herbs": "taze otlar", "kale": "kara lahana",
    "sucuk": "sucuk", "pastirma": "pastırma", "jam": "reçel", "tarragon": "tarhun otu",
    "salsa": "salsa sosu", "apricot": "kayısı", "caraway": "frenk kimyonu",
    "ouzo": "uzo", "buttermilk": "ayran", "marsala_wine": "marsala şarabı",
    "garam_masala": "garam masala", "hot_sauce": "acı sos", "pita": "pide",
    "bay_leaf": "defne yaprağı", "chicken_liver": "tavuk ciğeri",
    "prosciutto": "prosciutto", "beer": "bira", "egg_white": "yumurta akı",
    "fennel": "rezene", "wasabi": "wasabi", "horseradish": "yaban turpu",
    "crayfish": "kerevit", "shallot": "arpacık soğanı", "squid_ink": "kalamar mürekkebi",
    "pizza_dough": "pizza hamuru", "lobster": "ıstakoz", "celery_root": "kereviz kökü",
    "soba": "soba eriştesi", "puff_pastry": "milföy hamuru", "ricotta": "ricotta peyniri",
    "caramel": "karamel", "watermelon": "karpuz", "rice_paper": "pirinç kağıdı",
    "papaya": "papaya", "pear": "armut", "mango": "mango", "liver": "ciğer",
    "melon": "kavun", "chips": "cips", "ketchup": "ketçap", "seafood": "deniz ürünleri",
    "oyster": "istiridye", "purslane": "semizotu", "asparagus": "kuşkonmaz",
    "sumak": "sumak",
}


def token_to_tr(token):
    """Token'i Turkce isme cevir; bulunamazsa token'i temizle."""
    if token in TOKEN_TR:
        return TOKEN_TR[token]
    return token.replace("_", " ")
